/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AiRouteImport } from './routes/ai'
import { Route as BiRouteImport } from './routes/bi'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FoundersRouteImport } from './routes/founders'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MultiStoreRouteImport } from './routes/multi-store'
import { Route as PharmacyosRouteImport } from './routes/pharmacyos'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductTourRouteImport } from './routes/product-tour'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VisionMissionRouteImport } from './routes/vision-mission'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as PharmacyosAiRouteImport } from './routes/pharmacyos.ai'
import { Route as PharmacyosBillingRouteImport } from './routes/pharmacyos.billing'
import { Route as PharmacyosDashboardRouteImport } from './routes/pharmacyos.dashboard'
import { Route as PharmacyosInventoryRouteImport } from './routes/pharmacyos.inventory'
import { Route as PharmacyosOrdersRouteImport } from './routes/pharmacyos.orders'
import { Route as PharmacyosPrescriptionsRouteImport } from './routes/pharmacyos.prescriptions'
import { Route as PharmacyosStoreRouteImport } from './routes/pharmacyos.store'

const PharmacyosIndexLazyRouteImport = createFileRoute('/pharmacyos/')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/account.lazy').then((d) => d.Route))
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ai.lazy').then((d) => d.Route))
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/bi.lazy').then((d) => d.Route))
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/blog.lazy').then((d) => d.Route))
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/book-demo.lazy').then((d) => d.Route))
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/careers.lazy').then((d) => d.Route))
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/docs.lazy').then((d) => d.Route))
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/enterprise.lazy').then((d) => d.Route))
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/faq.lazy').then((d) => d.Route))
const FoundersRoute = FoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/get-started.lazy').then((d) => d.Route))
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/help.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const MultiStoreRoute = MultiStoreRouteImport.update({
  id: '/multi-store',
  path: '/multi-store',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/multi-store.lazy').then((d) => d.Route))
const PharmacyosRoute = PharmacyosRouteImport.update({
  id: '/pharmacyos',
  path: '/pharmacyos',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pharmacyos.lazy').then((d) => d.Route))
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pricing.lazy').then((d) => d.Route))
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))
const ProductTourRoute = ProductTourRouteImport.update({
  id: '/product-tour',
  path: '/product-tour',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/product-tour.lazy').then((d) => d.Route))
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/products.lazy').then((d) => d.Route))
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/refund.lazy').then((d) => d.Route))
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/security.lazy').then((d) => d.Route))
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/solutions.lazy').then((d) => d.Route))
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/terms.lazy').then((d) => d.Route))
const VisionMissionRoute = VisionMissionRouteImport.update({
  id: '/vision-mission',
  path: '/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/vision-mission.lazy').then((d) => d.Route),
)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.leads.lazy').then((d) => d.Route))
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any).lazy(() => import('./routes/blog.$slug.lazy').then((d) => d.Route))
const PharmacyosIndexLazyRoute = PharmacyosIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PharmacyosRoute,
} as any).lazy(() =>
  import('./routes/pharmacyos.index.lazy').then((d) => d.Route),
)
const PharmacyosAiRoute = PharmacyosAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => PharmacyosRoute,
} as any).lazy(() => import('./routes/pharmacyos.ai.lazy').then((d) => d.Route))
const PharmacyosBillingRoute = PharmacyosBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PharmacyosRoute,
} as any).lazy(() =>
  import('./routes/pharmacyos.billing.lazy').then((d) => d.Route),
)
const PharmacyosDashboardRoute = PharmacyosDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PharmacyosRoute,
} as any).lazy(() =>
  import('./routes/pharmacyos.dashboard.lazy').then((d) => d.Route),
)
const PharmacyosInventoryRoute = PharmacyosInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PharmacyosRoute,
} as any).lazy(() =>
  import('./routes/pharmacyos.inventory.lazy').then((d) => d.Route),
)
const PharmacyosOrdersRoute = PharmacyosOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PharmacyosRoute,
} as any).lazy(() =>
  import('./routes/pharmacyos.orders.lazy').then((d) => d.Route),
)
const PharmacyosPrescriptionsRoute = PharmacyosPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PharmacyosRoute,
} as any).lazy(() =>
  import('./routes/pharmacyos.prescriptions.lazy').then((d) => d.Route),
)
const PharmacyosStoreRoute = PharmacyosStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => PharmacyosRoute,
} as any).lazy(() =>
  import('./routes/pharmacyos.store.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ai': typeof AiRoute
  '/bi': typeof BiRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-demo': typeof BookDemoRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/get-started': typeof GetStartedRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/multi-store': typeof MultiStoreRoute
  '/pharmacyos': typeof PharmacyosRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product-tour': typeof ProductTourRoute
  '/products': typeof ProductsRoute
  '/refund': typeof RefundRoute
  '/security': typeof SecurityRoute
  '/solutions': typeof SolutionsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/vision-mission': typeof VisionMissionRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pharmacyos/ai': typeof PharmacyosAiRoute
  '/pharmacyos/billing': typeof PharmacyosBillingRoute
  '/pharmacyos/dashboard': typeof PharmacyosDashboardRoute
  '/pharmacyos/inventory': typeof PharmacyosInventoryRoute
  '/pharmacyos/orders': typeof PharmacyosOrdersRoute
  '/pharmacyos/prescriptions': typeof PharmacyosPrescriptionsRoute
  '/pharmacyos/store': typeof PharmacyosStoreRoute
  '/pharmacyos/': typeof PharmacyosIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ai': typeof AiRoute
  '/bi': typeof BiRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-demo': typeof BookDemoRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/get-started': typeof GetStartedRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/multi-store': typeof MultiStoreRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product-tour': typeof ProductTourRoute
  '/products': typeof ProductsRoute
  '/refund': typeof RefundRoute
  '/security': typeof SecurityRoute
  '/solutions': typeof SolutionsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/vision-mission': typeof VisionMissionRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pharmacyos/ai': typeof PharmacyosAiRoute
  '/pharmacyos/billing': typeof PharmacyosBillingRoute
  '/pharmacyos/dashboard': typeof PharmacyosDashboardRoute
  '/pharmacyos/inventory': typeof PharmacyosInventoryRoute
  '/pharmacyos/orders': typeof PharmacyosOrdersRoute
  '/pharmacyos/prescriptions': typeof PharmacyosPrescriptionsRoute
  '/pharmacyos/store': typeof PharmacyosStoreRoute
  '/pharmacyos': typeof PharmacyosIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/ai': typeof AiRoute
  '/bi': typeof BiRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-demo': typeof BookDemoRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/founders': typeof FoundersRoute
  '/get-started': typeof GetStartedRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/multi-store': typeof MultiStoreRoute
  '/pharmacyos': typeof PharmacyosRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/product-tour': typeof ProductTourRoute
  '/products': typeof ProductsRoute
  '/refund': typeof RefundRoute
  '/security': typeof SecurityRoute
  '/solutions': typeof SolutionsRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/vision-mission': typeof VisionMissionRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pharmacyos/ai': typeof PharmacyosAiRoute
  '/pharmacyos/billing': typeof PharmacyosBillingRoute
  '/pharmacyos/dashboard': typeof PharmacyosDashboardRoute
  '/pharmacyos/inventory': typeof PharmacyosInventoryRoute
  '/pharmacyos/orders': typeof PharmacyosOrdersRoute
  '/pharmacyos/prescriptions': typeof PharmacyosPrescriptionsRoute
  '/pharmacyos/store': typeof PharmacyosStoreRoute
  '/pharmacyos/': typeof PharmacyosIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/ai'
    | '/bi'
    | '/blog'
    | '/book-demo'
    | '/careers'
    | '/contact'
    | '/docs'
    | '/enterprise'
    | '/faq'
    | '/founders'
    | '/get-started'
    | '/help'
    | '/login'
    | '/multi-store'
    | '/pharmacyos'
    | '/pricing'
    | '/privacy'
    | '/product-tour'
    | '/products'
    | '/refund'
    | '/security'
    | '/solutions'
    | '/team'
    | '/terms'
    | '/vision-mission'
    | '/admin/leads'
    | '/blog/$slug'
    | '/pharmacyos/ai'
    | '/pharmacyos/billing'
    | '/pharmacyos/dashboard'
    | '/pharmacyos/inventory'
    | '/pharmacyos/orders'
    | '/pharmacyos/prescriptions'
    | '/pharmacyos/store'
    | '/pharmacyos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/ai'
    | '/bi'
    | '/blog'
    | '/book-demo'
    | '/careers'
    | '/contact'
    | '/docs'
    | '/enterprise'
    | '/faq'
    | '/founders'
    | '/get-started'
    | '/help'
    | '/login'
    | '/multi-store'
    | '/pricing'
    | '/privacy'
    | '/product-tour'
    | '/products'
    | '/refund'
    | '/security'
    | '/solutions'
    | '/team'
    | '/terms'
    | '/vision-mission'
    | '/admin/leads'
    | '/blog/$slug'
    | '/pharmacyos/ai'
    | '/pharmacyos/billing'
    | '/pharmacyos/dashboard'
    | '/pharmacyos/inventory'
    | '/pharmacyos/orders'
    | '/pharmacyos/prescriptions'
    | '/pharmacyos/store'
    | '/pharmacyos'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/ai'
    | '/bi'
    | '/blog'
    | '/book-demo'
    | '/careers'
    | '/contact'
    | '/docs'
    | '/enterprise'
    | '/faq'
    | '/founders'
    | '/get-started'
    | '/help'
    | '/login'
    | '/multi-store'
    | '/pharmacyos'
    | '/pricing'
    | '/privacy'
    | '/product-tour'
    | '/products'
    | '/refund'
    | '/security'
    | '/solutions'
    | '/team'
    | '/terms'
    | '/vision-mission'
    | '/admin/leads'
    | '/blog/$slug'
    | '/pharmacyos/ai'
    | '/pharmacyos/billing'
    | '/pharmacyos/dashboard'
    | '/pharmacyos/inventory'
    | '/pharmacyos/orders'
    | '/pharmacyos/prescriptions'
    | '/pharmacyos/store'
    | '/pharmacyos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AiRoute: typeof AiRoute
  BiRoute: typeof BiRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookDemoRoute: typeof BookDemoRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  EnterpriseRoute: typeof EnterpriseRoute
  FaqRoute: typeof FaqRoute
  FoundersRoute: typeof FoundersRoute
  GetStartedRoute: typeof GetStartedRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MultiStoreRoute: typeof MultiStoreRoute
  PharmacyosRoute: typeof PharmacyosRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductTourRoute: typeof ProductTourRoute
  ProductsRoute: typeof ProductsRoute
  RefundRoute: typeof RefundRoute
  SecurityRoute: typeof SecurityRoute
  SolutionsRoute: typeof SolutionsRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  VisionMissionRoute: typeof VisionMissionRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders': {
      id: '/founders'
      path: '/founders'
      fullPath: '/founders'
      preLoaderRoute: typeof FoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-store': {
      id: '/multi-store'
      path: '/multi-store'
      fullPath: '/multi-store'
      preLoaderRoute: typeof MultiStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacyos': {
      id: '/pharmacyos'
      path: '/pharmacyos'
      fullPath: '/pharmacyos'
      preLoaderRoute: typeof PharmacyosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-tour': {
      id: '/product-tour'
      path: '/product-tour'
      fullPath: '/product-tour'
      preLoaderRoute: typeof ProductTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision-mission': {
      id: '/vision-mission'
      path: '/vision-mission'
      fullPath: '/vision-mission'
      preLoaderRoute: typeof VisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/pharmacyos/': {
      id: '/pharmacyos/'
      path: '/'
      fullPath: '/pharmacyos/'
      preLoaderRoute: typeof PharmacyosIndexLazyRouteImport
      parentRoute: typeof PharmacyosRoute
    }
    '/pharmacyos/ai': {
      id: '/pharmacyos/ai'
      path: '/ai'
      fullPath: '/pharmacyos/ai'
      preLoaderRoute: typeof PharmacyosAiRouteImport
      parentRoute: typeof PharmacyosRoute
    }
    '/pharmacyos/billing': {
      id: '/pharmacyos/billing'
      path: '/billing'
      fullPath: '/pharmacyos/billing'
      preLoaderRoute: typeof PharmacyosBillingRouteImport
      parentRoute: typeof PharmacyosRoute
    }
    '/pharmacyos/dashboard': {
      id: '/pharmacyos/dashboard'
      path: '/dashboard'
      fullPath: '/pharmacyos/dashboard'
      preLoaderRoute: typeof PharmacyosDashboardRouteImport
      parentRoute: typeof PharmacyosRoute
    }
    '/pharmacyos/inventory': {
      id: '/pharmacyos/inventory'
      path: '/inventory'
      fullPath: '/pharmacyos/inventory'
      preLoaderRoute: typeof PharmacyosInventoryRouteImport
      parentRoute: typeof PharmacyosRoute
    }
    '/pharmacyos/orders': {
      id: '/pharmacyos/orders'
      path: '/orders'
      fullPath: '/pharmacyos/orders'
      preLoaderRoute: typeof PharmacyosOrdersRouteImport
      parentRoute: typeof PharmacyosRoute
    }
    '/pharmacyos/prescriptions': {
      id: '/pharmacyos/prescriptions'
      path: '/prescriptions'
      fullPath: '/pharmacyos/prescriptions'
      preLoaderRoute: typeof PharmacyosPrescriptionsRouteImport
      parentRoute: typeof PharmacyosRoute
    }
    '/pharmacyos/store': {
      id: '/pharmacyos/store'
      path: '/store'
      fullPath: '/pharmacyos/store'
      preLoaderRoute: typeof PharmacyosStoreRouteImport
      parentRoute: typeof PharmacyosRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PharmacyosRouteChildren {
  PharmacyosAiRoute: typeof PharmacyosAiRoute
  PharmacyosBillingRoute: typeof PharmacyosBillingRoute
  PharmacyosDashboardRoute: typeof PharmacyosDashboardRoute
  PharmacyosInventoryRoute: typeof PharmacyosInventoryRoute
  PharmacyosOrdersRoute: typeof PharmacyosOrdersRoute
  PharmacyosPrescriptionsRoute: typeof PharmacyosPrescriptionsRoute
  PharmacyosStoreRoute: typeof PharmacyosStoreRoute
  PharmacyosIndexLazyRoute: typeof PharmacyosIndexLazyRoute
}

const PharmacyosRouteChildren: PharmacyosRouteChildren = {
  PharmacyosAiRoute: PharmacyosAiRoute,
  PharmacyosBillingRoute: PharmacyosBillingRoute,
  PharmacyosDashboardRoute: PharmacyosDashboardRoute,
  PharmacyosInventoryRoute: PharmacyosInventoryRoute,
  PharmacyosOrdersRoute: PharmacyosOrdersRoute,
  PharmacyosPrescriptionsRoute: PharmacyosPrescriptionsRoute,
  PharmacyosStoreRoute: PharmacyosStoreRoute,
  PharmacyosIndexLazyRoute: PharmacyosIndexLazyRoute,
}

const PharmacyosRouteWithChildren = PharmacyosRoute._addFileChildren(
  PharmacyosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AiRoute: AiRoute,
  BiRoute: BiRoute,
  BlogRoute: BlogRouteWithChildren,
  BookDemoRoute: BookDemoRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  EnterpriseRoute: EnterpriseRoute,
  FaqRoute: FaqRoute,
  FoundersRoute: FoundersRoute,
  GetStartedRoute: GetStartedRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MultiStoreRoute: MultiStoreRoute,
  PharmacyosRoute: PharmacyosRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductTourRoute: ProductTourRoute,
  ProductsRoute: ProductsRoute,
  RefundRoute: RefundRoute,
  SecurityRoute: SecurityRoute,
  SolutionsRoute: SolutionsRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  VisionMissionRoute: VisionMissionRoute,
  AdminLeadsRoute: AdminLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
